name: qtf-pre-pheat-reproduction
channels:
  - conda-forge
dependencies:
  - python >=3.12,<3.13
  - pip
  - gromacs >=2026
  - openmm
  - matplotlib >=3.7
  - mdtraj >=1.9
  - biopython >=1.80
  - pip:
      - -e .[dev,workflows]
